# Stubs for xlsxwriter (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from .workbook import Workbook as Workbook

__VERSION__ = ...  # type: Any
