# Stubs for xlsxwriter.chart (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
#import xmlwriter
#from .shape import Shape as Shape
#from .utility import get_rgb_color as get_rgb_color
#from .utility import xl_rowcol_to_cell as xl_rowcol_to_cell
#from .utility import xl_range_formula as xl_range_formula
#from .utility import supported_datetime as supported_datetime
#from .utility import datetime_to_excel_datetime as datetime_to_excel_datetime
#from .utility import quote_sheetname as quote_sheetname

class Chart: #(xmlwriter.XMLwriter):
    subtype = ...  # type: Any
    sheet_type = ...  # type: Any
    orientation = ...  # type: Any
    series = ...  # type: Any
    embedded = ...  # type: Any
    id = ...  # type: Any
    series_index = ...  # type: Any
    style_id = ...  # type: Any
    axis_ids = ...  # type: Any
    axis2_ids = ...  # type: Any
    cat_has_num_fmt = ...  # type: Any
    requires_category = ...  # type: Any
    legend_position = ...  # type: Any
    legend_delete_series = ...  # type: Any
    legend_font = ...  # type: Any
    legend_layout = ...  # type: Any
    cat_axis_position = ...  # type: Any
    val_axis_position = ...  # type: Any
    formula_ids = ...  # type: Any
    formula_data = ...  # type: Any
    horiz_cat_axis = ...  # type: Any
    horiz_val_axis = ...  # type: Any
    protection = ...  # type: Any
    chartarea = ...  # type: Any
    plotarea = ...  # type: Any
    x_axis = ...  # type: Any
    y_axis = ...  # type: Any
    y2_axis = ...  # type: Any
    x2_axis = ...  # type: Any
    chart_name = ...  # type: Any
    show_blanks = ...  # type: Any
    show_hidden = ...  # type: Any
    show_crosses = ...  # type: Any
    width = ...  # type: Any
    height = ...  # type: Any
    x_scale = ...  # type: Any
    y_scale = ...  # type: Any
    x_offset = ...  # type: Any
    y_offset = ...  # type: Any
    table = ...  # type: Any
    cross_between = ...  # type: Any
    default_marker = ...  # type: Any
    series_gap_1 = ...  # type: Any
    series_gap_2 = ...  # type: Any
    series_overlap_1 = ...  # type: Any
    series_overlap_2 = ...  # type: Any
    drop_lines = ...  # type: Any
    hi_low_lines = ...  # type: Any
    up_down_bars = ...  # type: Any
    smooth_allowed = ...  # type: Any
    title_font = ...  # type: Any
    title_name = ...  # type: Any
    title_formula = ...  # type: Any
    title_data_id = ...  # type: Any
    title_layout = ...  # type: Any
    title_overlay = ...  # type: Any
    title_none = ...  # type: Any
    date_category = ...  # type: Any
    date_1904 = ...  # type: Any
    label_positions = ...  # type: Any
    label_position_default = ...  # type: Any
    already_inserted = ...  # type: Any
    combined = ...  # type: Any
    is_secondary = ...  # type: Any
    def __init__(self, options=None): ...
    fill = ...  # type: Any
    def add_series(self, options): ...
    def set_x_axis(self, options): ...
    def set_y_axis(self, options): ...
    def set_x2_axis(self, options): ...
    def set_y2_axis(self, options): ...
    def set_title(self, options): ...
    def set_legend(self, options): ...
    def set_plotarea(self, options): ...
    def set_chartarea(self, options): ...
    def set_style(self, style_id): ...
    def show_blanks_as(self, option): ...
    def show_hidden_data(self): ...
    def set_size(self, options): ...
    def set_table(self, options=None): ...
    def set_up_down_bars(self, options=None): ...
    def set_drop_lines(self, options=None): ...
    def set_high_low_lines(self, options=None): ...
    def combine(self, chart=None): ...
