# Stubs for xlsxwriter.workbook (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
#from .compatibility import str_types as str_types, force_unicode as force_unicode
#from .utility import xl_cell_to_rowcol as xl_cell_to_rowcol

class Workbook: #(xmlwriter.XMLwriter):
    filename = ...  # type: Any
    tmpdir = ...  # type: Any
    date_1904 = ...  # type: Any
    strings_to_numbers = ...  # type: Any
    strings_to_formulas = ...  # type: Any
    strings_to_urls = ...  # type: Any
    nan_inf_to_errors = ...  # type: Any
    default_date_format = ...  # type: Any
    optimization = ...  # type: Any
    in_memory = ...  # type: Any
    excel2003_style = ...  # type: Any
    default_format_properties = ...  # type: Any
    worksheet_meta = ...  # type: Any
    selected = ...  # type: Any
    fileclosed = ...  # type: Any
    filehandle = ...  # type: Any
    internal_fh = ...  # type: Any
    sheet_name = ...  # type: Any
    chart_name = ...  # type: Any
    sheetname_count = ...  # type: Any
    chartname_count = ...  # type: Any
    worksheets_objs = ...  # type: Any
    charts = ...  # type: Any
    drawings = ...  # type: Any
    sheetnames = ...  # type: Any
    formats = ...  # type: Any
    xf_formats = ...  # type: Any
    xf_format_indices = ...  # type: Any
    dxf_formats = ...  # type: Any
    dxf_format_indices = ...  # type: Any
    palette = ...  # type: Any
    font_count = ...  # type: Any
    num_format_count = ...  # type: Any
    defined_names = ...  # type: Any
    named_ranges = ...  # type: Any
    custom_colors = ...  # type: Any
    doc_properties = ...  # type: Any
    createtime = ...  # type: Any
    num_vml_files = ...  # type: Any
    num_comment_files = ...  # type: Any
    x_window = ...  # type: Any
    y_window = ...  # type: Any
    window_width = ...  # type: Any
    window_height = ...  # type: Any
    tab_ratio = ...  # type: Any
    str_table = ...  # type: Any
    vba_project = ...  # type: Any
    vba_is_stream = ...  # type: Any
    vba_codename = ...  # type: Any
    image_types = ...  # type: Any
    images = ...  # type: Any
    border_count = ...  # type: Any
    fill_count = ...  # type: Any
    drawing_count = ...  # type: Any
    calc_mode = ...  # type: Any
    calc_on_load = ...  # type: Any
    allow_zip64 = ...  # type: Any
    calc_id = ...  # type: Any
    default_url_format = ...  # type: Any
    def __init__(self, filename=None, options=...): ...
    def __del__(self): ...
    def __enter__(self): ...
    def __exit__(self, type, value, traceback): ...
    def add_worksheet(self, name=None): ...
    def add_chartsheet(self, name=None): ...
    def add_format(self, properties=...): ...
    def add_chart(self, options): ...
    def add_vba_project(self, vba_project, is_stream=False): ...
    def close(self): ...
    def set_properties(self, properties): ...
    def set_calc_mode(self, mode, calc_id=None): ...
    def define_name(self, name, formula): ...
    def worksheets(self): ...
    def get_worksheet_by_name(self, name): ...
    def use_zip64(self): ...
    def set_vba_name(self, name=None): ...

class WorksheetMeta:
    activesheet = ...  # type: Any
    firstsheet = ...  # type: Any
    def __init__(self): ...
