# Stubs for xlsxwriter.worksheet (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
#import xmlwriter
#from .compatibility import StringIO as StringIO
#from .compatibility import defaultdict as defaultdict
#from .compatibility import namedtuple as namedtuple
#from .compatibility import force_unicode as force_unicode
#from .compatibility import num_types as num_types, str_types as str_types
#from .format import Format as Format
#from .drawing import Drawing as Drawing
#from .shape import Shape as Shape
#from .xmlwriter import XMLwriter as XMLwriter
#from .utility import xl_rowcol_to_cell as xl_rowcol_to_cell
#from .utility import xl_rowcol_to_cell_fast as xl_rowcol_to_cell_fast
#from .utility import xl_cell_to_rowcol as xl_cell_to_rowcol
#from .utility import xl_col_to_name as xl_col_to_name
#from .utility import xl_range as xl_range
#from .utility import xl_color as xl_color
#from .utility import get_sparkline_style as get_sparkline_style
#from .utility import supported_datetime as supported_datetime
#from .utility import datetime_to_excel_datetime as datetime_to_excel_datetime
#from .utility import quote_sheetname as quote_sheetname
from collections import namedtuple

def convert_cell_args(method): ...
def convert_range_args(method): ...
def convert_column_args(method): ...

cell_string_tuple = namedtuple('String', 'string, format')

cell_number_tuple = namedtuple('Number', 'number, format')

cell_blank_tuple = namedtuple('Blank', 'format')

cell_boolean_tuple = namedtuple('Boolean', 'boolean, format')

cell_formula_tuple = namedtuple('Formula', 'formula, format, value')

cell_arformula_tuple = namedtuple('ArrayFormula', 'formula, format, value, range')

class Worksheet: #(xmlwriter.XMLwriter):
    name = ...  # type: Any
    index = ...  # type: Any
    str_table = ...  # type: Any
    palette = ...  # type: Any
    optimization = ...  # type: Any
    tmpdir = ...  # type: Any
    is_chartsheet = ...  # type: Any
    ext_sheets = ...  # type: Any
    fileclosed = ...  # type: Any
    excel_version = ...  # type: Any
    excel2003_style = ...  # type: Any
    xls_rowmax = ...  # type: Any
    xls_colmax = ...  # type: Any
    xls_strmax = ...  # type: Any
    dim_rowmin = ...  # type: Any
    dim_rowmax = ...  # type: Any
    dim_colmin = ...  # type: Any
    dim_colmax = ...  # type: Any
    colinfo = ...  # type: Any
    selections = ...  # type: Any
    hidden = ...  # type: Any
    active = ...  # type: Any
    tab_color = ...  # type: Any
    panes = ...  # type: Any
    active_pane = ...  # type: Any
    selected = ...  # type: Any
    page_setup_changed = ...  # type: Any
    paper_size = ...  # type: Any
    orientation = ...  # type: Any
    print_options_changed = ...  # type: Any
    hcenter = ...  # type: Any
    vcenter = ...  # type: Any
    print_gridlines = ...  # type: Any
    screen_gridlines = ...  # type: Any
    print_headers = ...  # type: Any
    header_footer_changed = ...  # type: Any
    header = ...  # type: Any
    footer = ...  # type: Any
    header_footer_aligns = ...  # type: Any
    header_footer_scales = ...  # type: Any
    header_images = ...  # type: Any
    footer_images = ...  # type: Any
    header_images_list = ...  # type: Any
    margin_left = ...  # type: Any
    margin_right = ...  # type: Any
    margin_top = ...  # type: Any
    margin_bottom = ...  # type: Any
    margin_header = ...  # type: Any
    margin_footer = ...  # type: Any
    repeat_row_range = ...  # type: Any
    repeat_col_range = ...  # type: Any
    print_area_range = ...  # type: Any
    page_order = ...  # type: Any
    black_white = ...  # type: Any
    draft_quality = ...  # type: Any
    print_comments = ...  # type: Any
    page_start = ...  # type: Any
    fit_page = ...  # type: Any
    fit_width = ...  # type: Any
    fit_height = ...  # type: Any
    hbreaks = ...  # type: Any
    vbreaks = ...  # type: Any
    protect_options = ...  # type: Any
    set_cols = ...  # type: Any
    set_rows = ...  # type: Any
    zoom = ...  # type: Any
    zoom_scale_normal = ...  # type: Any
    print_scale = ...  # type: Any
    is_right_to_left = ...  # type: Any
    show_zeros = ...  # type: Any
    leading_zeros = ...  # type: Any
    outline_row_level = ...  # type: Any
    outline_col_level = ...  # type: Any
    outline_style = ...  # type: Any
    outline_below = ...  # type: Any
    outline_right = ...  # type: Any
    outline_on = ...  # type: Any
    outline_changed = ...  # type: Any
    original_row_height = ...  # type: Any
    default_row_height = ...  # type: Any
    default_row_pixels = ...  # type: Any
    default_col_pixels = ...  # type: Any
    default_row_zeroed = ...  # type: Any
    names = ...  # type: Any
    write_match = ...  # type: Any
    table = ...  # type: Any
    merge = ...  # type: Any
    row_spans = ...  # type: Any
    has_vml = ...  # type: Any
    has_header_vml = ...  # type: Any
    has_comments = ...  # type: Any
    comments = ...  # type: Any
    comments_list = ...  # type: Any
    comments_author = ...  # type: Any
    comments_visible = ...  # type: Any
    vml_shape_id = ...  # type: Any
    buttons_list = ...  # type: Any
    vml_header_id = ...  # type: Any
    autofilter_area = ...  # type: Any
    autofilter_ref = ...  # type: Any
    filter_range = ...  # type: Any
    filter_on = ...  # type: Any
    filter_cols = ...  # type: Any
    filter_type = ...  # type: Any
    col_sizes = ...  # type: Any
    row_sizes = ...  # type: Any
    col_formats = ...  # type: Any
    col_size_changed = ...  # type: Any
    row_size_changed = ...  # type: Any
    last_shape_id = ...  # type: Any
    rel_count = ...  # type: Any
    hlink_count = ...  # type: Any
    hlink_refs = ...  # type: Any
    external_hyper_links = ...  # type: Any
    external_drawing_links = ...  # type: Any
    external_comment_links = ...  # type: Any
    external_vml_links = ...  # type: Any
    external_table_links = ...  # type: Any
    drawing_links = ...  # type: Any
    vml_drawing_links = ...  # type: Any
    charts = ...  # type: Any
    images = ...  # type: Any
    tables = ...  # type: Any
    sparklines = ...  # type: Any
    shapes = ...  # type: Any
    shape_hash = ...  # type: Any
    drawing = ...  # type: Any
    rstring = ...  # type: Any
    previous_row = ...  # type: Any
    validations = ...  # type: Any
    cond_formats = ...  # type: Any
    dxf_priority = ...  # type: Any
    page_view = ...  # type: Any
    vba_codename = ...  # type: Any
    date_1904 = ...  # type: Any
    hyperlinks = ...  # type: Any
    strings_to_numbers = ...  # type: Any
    strings_to_urls = ...  # type: Any
    nan_inf_to_errors = ...  # type: Any
    strings_to_formulas = ...  # type: Any
    default_date_format = ...  # type: Any
    default_url_format = ...  # type: Any
    row_data_filename = ...  # type: Any
    row_data_fh = ...  # type: Any
    worksheet_meta = ...  # type: Any
    vml_data_id = ...  # type: Any
    row_data_fh_closed = ...  # type: Any
    vertical_dpi = ...  # type: Any
    horizontal_dpi = ...  # type: Any
    def __init__(self): ...
    def write(self, row, col, *args): ...
    def write_string(self, row, col, string, cell_format=None): ...
    def write_number(self, row, col, number, cell_format=None): ...
    def write_blank(self, row, col, blank, cell_format=None): ...
    def write_formula(self, row, col, formula, cell_format=None, value=0): ...
    def write_array_formula(self, first_row, first_col, last_row, last_col, formula, cell_format=None, value=0): ...
    def write_datetime(self, row, col, date, cell_format=None): ...
    def write_boolean(self, row, col, boolean, cell_format=None): ...
    def write_url(self, row, col, url, cell_format=None, string=None, tip=None): ...
    def write_rich_string(self, row, col, *args): ...
    def write_row(self, row, col, data, cell_format=None): ...
    def write_column(self, row, col, data, cell_format=None): ...
    def insert_image(self, row, col, filename, options=...): ...
    def insert_textbox(self, row, col, text, options=None): ...
    def insert_chart(self, row, col, chart, options=...): ...
    def write_comment(self, row, col, comment, options=...): ...
    def show_comments(self): ...
    def set_comments_author(self, author): ...
    def get_name(self): ...
    def activate(self): ...
    def select(self): ...
    def hide(self): ...
    def set_first_sheet(self): ...
    def set_column(self, firstcol, lastcol, width=None, cell_format=None, options=...): ...
    def set_row(self, row, height=None, cell_format=None, options=...): ...
    def set_default_row(self, height=None, hide_unused_rows=False): ...
    def merge_range(self, first_row, first_col, last_row, last_col, data, cell_format=None): ...
    def autofilter(self, first_row, first_col, last_row, last_col): ...
    def filter_column(self, col, criteria): ...
    def filter_column_list(self, col, filters): ...
    def data_validation(self, first_row, first_col, last_row, last_col, options): ...
    def conditional_format(self, first_row, first_col, last_row, last_col, options=None): ...
    def add_table(self, first_row, first_col, last_row, last_col, options=None): ...
    def add_sparkline(self, row, col, options): ...
    def set_selection(self, first_row, first_col, last_row, last_col): ...
    def outline_settings(self, outline_on=1, outline_below=1, outline_right=1, outline_style=0): ...
    def freeze_panes(self, row, col, top_row=None, left_col=None, pane_type=0): ...
    def split_panes(self, x, y, top_row=None, left_col=None): ...
    def set_zoom(self, zoom=100): ...
    def right_to_left(self): ...
    def hide_zero(self): ...
    def set_tab_color(self, color): ...
    def protect(self, password='', options=None): ...
    def insert_button(self, row, col, options=...): ...
    def set_landscape(self): ...
    def set_portrait(self): ...
    def set_page_view(self): ...
    def set_paper(self, paper_size): ...
    def center_horizontally(self): ...
    def center_vertically(self): ...
    def set_margins(self, left=0.0, right=0.0, top=0.0, bottom=0.0): ...
    def set_header(self, header='', options=None, margin=None): ...
    def set_footer(self, footer='', options=None, margin=None): ...
    def repeat_rows(self, first_row, last_row=None): ...
    def repeat_columns(self, first_col, last_col=None): ...
    def hide_gridlines(self, option=1): ...
    def print_row_col_headers(self): ...
    def print_area(self, first_row, first_col, last_row, last_col): ...
    def print_across(self): ...
    def fit_to_pages(self, width, height): ...
    def set_start_page(self, start_page): ...
    def set_print_scale(self, scale): ...
    def set_h_pagebreaks(self, breaks): ...
    def set_v_pagebreaks(self, breaks): ...
    def set_vba_name(self, name=None): ...
