# Stubs for numpy.compat._inspect (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def getargspec(func): ...
def formatargspec(args, varargs: Optional[Any] = ..., varkw: Optional[Any] = ..., defaults: Optional[Any] = ..., formatarg: Any = ..., formatvarargs: Any = ..., formatvarkw: Any = ..., formatvalue: Any = ..., join: Any = ...): ...
