# Stubs for numpy.distutils (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from .__version__ import version as __version__
from .info import __doc__ as __doc__
from .npy_pkg_config import *

test = ...  # type: Any
