# Stubs for numpy.distutils.__version__ (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

major = ...  # type: int
minor = ...  # type: int
micro = ...  # type: int
version = ...  # type: Any
