# Stubs for numpy.distutils.core (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from distutils.core import *
from setuptools import setup as old_setup
from distutils.core import setup as old_setup

have_setuptools = ...  # type: bool
numpy_cmdclass = ...  # type: Any

def get_distribution(always: bool = ...): ...
def setup(**attr): ...
