# Stubs for numpy.distutils.exec_command (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def find_executable(exe, path: Optional[Any] = ..., _cache: Any = ...): ...
def exec_command(command, execute_in: str = ..., use_shell: Optional[Any] = ..., use_tee: Optional[Any] = ..., _with_python: int = ..., **env): ...
