# Stubs for numpy.distutils.intelccompiler (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from distutils.unixccompiler import UnixCCompiler

class IntelCCompiler(UnixCCompiler):
    compiler_type = ...  # type: str
    cc_exe = ...  # type: str
    cc_args = ...  # type: str
    def __init__(self, verbose: int = ..., dry_run: int = ..., force: int = ...) -> None: ...

class IntelItaniumCCompiler(IntelCCompiler):
    compiler_type = ...  # type: str

class IntelEM64TCCompiler(UnixCCompiler):
    compiler_type = ...  # type: str
    cc_exe = ...  # type: str
    cc_args = ...  # type: str
    def __init__(self, verbose: int = ..., dry_run: int = ..., force: int = ...) -> None: ...

class IntelCCompilerW(MSVCCompiler):
    compiler_type = ...  # type: str
    compiler_cxx = ...  # type: str
    def __init__(self, verbose: int = ..., dry_run: int = ..., force: int = ...) -> None: ...
    cc = ...  # type: Any
    lib = ...  # type: Any
    linker = ...  # type: Any
    compile_options = ...  # type: Any
    compile_options_debug = ...  # type: Any
    def initialize(self, plat_name: Optional[Any] = ...): ...

class IntelEM64TCCompilerW(IntelCCompilerW):
    compiler_type = ...  # type: str
    def __init__(self, verbose: int = ..., dry_run: int = ..., force: int = ...) -> None: ...
