# Stubs for numpy.distutils.msvccompiler (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from distutils.msvccompiler import MSVCCompiler as _MSVCCompiler
from .system_info import platform_bits as platform_bits

class MSVCCompiler(_MSVCCompiler):
    def __init__(self, verbose: int = ..., dry_run: int = ..., force: int = ...) -> None: ...
    def initialize(self, plat_name: Optional[Any] = ...): ...
