# Stubs for numpy.distutils.unixccompiler (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from distutils.unixccompiler import *

def UnixCCompiler__compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts): ...
def UnixCCompiler_create_static_lib(self, objects, output_libname, output_dir: Optional[Any] = ..., debug: int = ..., target_lang: Optional[Any] = ...): ...
