# Stubs for numpy.core._methods (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from numpy.core import multiarray as mu
from numpy.core import umath as um
from numpy.core import numerictypes as nt

umr_maximum = ...  # type: Any
umr_minimum = ...  # type: Any
umr_sum = ...  # type: Any
umr_prod = ...  # type: Any
umr_any = ...  # type: Any
umr_all = ...  # type: Any
