# Stubs for numpy.core.function_base (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from . import numeric as _nx

def linspace(start, stop, num: int = ..., endpoint: bool = ..., retstep: bool = ..., dtype: Optional[Any] = ...): ...
def logspace(start, stop, num: int = ..., endpoint: bool = ..., base: float = ..., dtype: Optional[Any] = ...): ...
