# Stubs for numpy.core.getlimits (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from . import numerictypes as ntypes

class finfo:
    def __new__(cls, dtype): ...

class iinfo:
    dtype = ...  # type: Any
    kind = ...  # type: Any
    bits = ...  # type: Any
    key = ...  # type: Any
    def __init__(self, int_type) -> None: ...
    def min(self): ...
    def max(self): ...
