# Stubs for numpy.core.machar (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class MachAr:
    def __init__(self, float_conv: Any = ..., int_conv: Any = ..., float_to_float: Any = ..., float_to_str: Any = ..., title: str = ...) -> None: ...
