# Stubs for numpy.core.setup_common (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

C_ABI_VERSION = ...  # type: int
C_API_VERSION = ...  # type: int

class MismatchCAPIWarning(Warning): ...

def is_released(config): ...
def get_api_versions(apiversion, codegen_dir): ...
def check_api_version(apiversion, codegen_dir): ...

MANDATORY_FUNCS = ...  # type: Any
OPTIONAL_STDFUNCS = ...  # type: Any
OPTIONAL_HEADERS = ...  # type: Any
OPTIONAL_INTRINSICS = ...  # type: Any
OPTIONAL_FUNCTION_ATTRIBUTES = ...  # type: Any
OPTIONAL_VARIABLE_ATTRIBUTES = ...  # type: Any
OPTIONAL_STDFUNCS_MAYBE = ...  # type: Any
C99_FUNCS = ...  # type: Any
C99_FUNCS_SINGLE = ...  # type: Any
C99_FUNCS_EXTENDED = ...  # type: Any
C99_COMPLEX_TYPES = ...  # type: Any
C99_COMPLEX_FUNCS = ...  # type: Any

def fname2def(name): ...
def sym2def(symbol): ...
def type2def(symbol): ...
def check_long_double_representation(cmd): ...

LONG_DOUBLE_REPRESENTATION_SRC = ...  # type: str

def pyod(filename): ...
def long_double_representation(lines): ...
