# Stubs for numpy (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from ._globals import ModuleDeprecationWarning as ModuleDeprecationWarning, VisibleDeprecationWarning as VisibleDeprecationWarning
from numpy.__config__ import show as show_config
from .version import git_revision as __git_revision__
from .version import version as __version__
from ._import_tools import PackageLoader
from .core import *
from .lib import *
from . import matrixlib as _mat
from .matrixlib import *
from .compat import long as long
import random
from . import ma

def median(*_, **_2): ...
def histogram(*_, **_2): ...
def pkgload(*packages, **options): ...
def add_newdoc(*_, **_2): ...
def angle(*_, **_2): ...
def append(*_, **_2): ...
def apply_along_axis(*_, **_2): ...
def apply_over_axes(*_, **_2): ...
def array_split(*_, **_2): ...
def asarray_chkfinite(*_, **_2): ...
def asfarray(*_, **_2): ...
def asscalar(*_, **_2): ...
#def atleast_1d(*_, **_2): ...
#def atleast_2d(*_, **_2): ...
#def atleast_3d(*_, **_2): ...
def average(*_, **_2): ...
def bartlett(*_, **_2): ...
def blackman(*_, **_2): ...
def broadcast_arrays(*_, **_2): ...
def broadcast_to(*_, **_2): ...
def byte_bounds(*_, **_2): ...
def column_stack(*_, **_2): ...
def common_type(*_, **_2): ...
def copy(*_, **_2): ...
def corrcoef(*_, **_2): ...
def cov(*_, **_2): ...
def delete(*_, **_2): ...
def deprecate(*_, **_2): ...
def deprecate_with_doc(*_, **_2): ...
def diag(*_, **_2): ...
def diag_indices(*_, **_2): ...
def diag_indices_from(*_, **_2): ...
def diagflat(*_, **_2): ...
def diff(*_, **_2): ...
def disp(*_, **_2): ...
def dsplit(*_, **_2): ...
def dstack(*_, **_2): ...
def ediff1d(*_, **_2): ...
def expand_dims(*_, **_2): ...
def extract(*_, **_2): ...
def eye(*_, **_2): ...
def fill_diagonal(*_, **_2): ...
def fix(*_, **_2): ...
def fliplr(*_, **_2): ...
def flipud(*_, **_2): ...
def fromregex(*_, **_2): ...
def fv(*_, **_2): ...
def genfromtxt(*_, **_2): ...
def get_array_wrap(*_, **_2): ...
def get_include(*_, **_2): ...
def gradient(*_, **_2): ...
def hamming(*_, **_2): ...
def hanning(*_, **_2): ...
def histogram2d(*_, **_2): ...
def histogramdd(*_, **_2): ...
def hsplit(*_, **_2): ...
def i0(*_, **_2): ...
def imag(*_, **_2): ...
def in1d(*_, **_2): ...
def info(*_, **_2): ...
def insert(*_, **_2): ...
def interp(*_, **_2): ...
def intersect1d(*_, **_2): ...
def ipmt(*_, **_2): ...
def irr(*_, **_2): ...
def iscomplex(*_, **_2): ...
def iscomplexobj(*_, **_2): ...
def isneginf(*_, **_2): ...
def isposinf(*_, **_2): ...
def isreal(*_, **_2): ...
def isrealobj(*_, **_2): ...
def issubclass_(*_, **_2): ...
def iterable(*_, **_2): ...
def ix_(*_, **_2): ...
def kaiser(*_, **_2): ...
def kron(*_, **_2): ...
def loadtxt(*_, **_2): ...
def lookfor(*_, **_2): ...
def mafromtxt(*_, **_2): ...
def mask_indices(*_, **_2): ...
def meshgrid(*_, **_2): ...
def mintypecode(*_, **_2): ...
def mirr(*_, **_2): ...
def msort(*_, **_2): ...
def nan_to_num(*_, **_2): ...
def nanargmax(*_, **_2): ...
def nanargmin(*_, **_2): ...
def nanmax(*_, **_2): ...
def nanmean(*_, **_2): ...
def nanmedian(*_, **_2): ...
def nanmin(*_, **_2): ...
def nanpercentile(*_, **_2): ...
def nanprod(*_, **_2): ...
def nanstd(*_, **_2): ...
def nansum(*_, **_2): ...
def nanvar(*_, **_2): ...
def ndfromtxt(*_, **_2): ...
def nper(*_, **_2): ...
def npv(*_, **_2): ...
def pad(*_, **_2): ...
def percentile(*_, **_2): ...
def piecewise(*_, **_2): ...
def place(*_, **_2): ...
def pmt(*_, **_2): ...
def poly(*_, **_2): ...
def polyadd(*_, **_2): ...
def polyder(*_, **_2): ...
def polydiv(*_, **_2): ...
def polyfit(*_, **_2): ...
def polyint(*_, **_2): ...
def polymul(*_, **_2): ...
def polysub(*_, **_2): ...
def polyval(*_, **_2): ...
def ppmt(*_, **_2): ...
def pv(*_, **_2): ...
def rate(*_, **_2): ...
def real(*_, **_2): ...
def real_if_close(*_, **_2): ...
def recfromcsv(*_, **_2): ...
def recfromtxt(*_, **_2): ...
def roots(*_, **_2): ...
def rot90(*_, **_2): ...
def row_stack(*_, **_2): ...
def safe_eval(*_, **_2): ...
def save(*_, **_2): ...
def savetxt(*_, **_2): ...
def savez(*_, **_2): ...
def savez_compressed(*_, **_2): ...
def select(*_, **_2): ...
def setdiff1d(*_, **_2): ...
def setxor1d(*_, **_2): ...
def sinc(*_, **_2): ...
def sort_complex(*_, **_2): ...
def source(*_, **_2): ...
def split(*_, **_2): ...
def tile(*_, **_2): ...
def trapz(*_, **_2): ...
def tri(*_, **_2): ...
def tril(*_, **_2): ...
def tril_indices(*_, **_2): ...
def tril_indices_from(*_, **_2): ...
def trim_zeros(*_, **_2): ...
def triu(*_, **_2): ...
def triu_indices(*_, **_2): ...
def triu_indices_from(*_, **_2): ...
def typename(*_, **_2): ...
def union1d(*_, **_2): ...
def unique(*_, **_2): ...
def unwrap(*_, **_2): ...
def vander(*_, **_2): ...
def vsplit(*_, **_2): ...
def who(*_, **_2): ...


# Names in __all__ with no definition:
#   ALLOW_THREADS
#   BUFSIZE
#   CLIP
#   ComplexWarning
#   DataSource
#   ERR_CALL
#   ERR_DEFAULT
#   ERR_IGNORE
#   ERR_LOG
#   ERR_PRINT
#   ERR_RAISE
#   ERR_WARN
#   FLOATING_POINT_SUPPORT
#   FPE_DIVIDEBYZERO
#   FPE_INVALID
#   FPE_OVERFLOW
#   FPE_UNDERFLOW
#   False_
#   Inf
#   Infinity
#   MAXDIMS
#   MAY_SHARE_BOUNDS
#   MAY_SHARE_EXACT
#   MachAr
#   NAN
#   NINF
#   NZERO
#   NaN
#   PINF
#   PZERO
#   RAISE
#   RankWarning
#   SHIFT_DIVIDEBYZERO
#   SHIFT_INVALID
#   SHIFT_OVERFLOW
#   SHIFT_UNDERFLOW
#   ScalarType
#   TooHardError
#   True_
#   UFUNC_BUFSIZE_DEFAULT
#   UFUNC_PYVALS_NAME
#   WRAP
#   __version__
#   absolute
#   add
#   add_docstring
#   add_newdoc
#   add_newdoc_ufunc
#   add_newdocs
#   alen
#   alen
#   all
#   all
#   allclose
#   alltrue
#   alltrue
#   alterdot
#   amax
#   amax
#   amin
#   amin
#   angle
#   any
#   any
#   append
#   apply_along_axis
#   apply_over_axes
#   arange
#   arccos
#   arccosh
#   arcsin
#   arcsinh
#   arctan
#   arctan2
#   arctanh
#   argmax
#   argmax
#   argmin
#   argmin
#   argpartition
#   argpartition
#   argsort
#   argsort
#   argwhere
#   around
#   around
#   array
#   array2string
#   array_equal
#   array_equiv
#   array_repr
#   array_split
#   array_str
#   asanyarray
#   asarray
#   asarray_chkfinite
#   ascontiguousarray
#   asfarray
#   asfortranarray
#   asmatrix
#   asscalar
#   atleast_1d
#   atleast_2d
#   atleast_3d
#   average
#   bartlett
#   base_repr
#   binary_repr
#   bincount
#   bitwise_and
#   bitwise_not
#   bitwise_or
#   bitwise_xor
#   blackman
#   bmat
#   bool8
#   bool_
#   broadcast
#   broadcast_arrays
#   broadcast_to
#   busday_count
#   busday_offset
#   busdaycalendar
#   byte
#   byte_bounds
#   bytes0
#   bytes_
#   c_
#   can_cast
#   cast
#   cbrt
#   cdouble
#   ceil
#   cfloat
#   char
#   character
#   chararray
#   choose
#   choose
#   clip
#   clip
#   clongdouble
#   clongfloat
#   column_stack
#   common_type
#   compare_chararrays
#   complex128
#   complex256
#   complex64
#   complex_
#   complexfloating
#   compress
#   compress
#   concatenate
#   conj
#   conjugate
#   convolve
#   copy
#   copysign
#   copyto
#   corrcoef
#   correlate
#   cos
#   cosh
#   count_nonzero
#   cov
#   cross
#   csingle
#   ctypeslib
#   cumprod
#   cumprod
#   cumproduct
#   cumproduct
#   cumsum
#   cumsum
#   datetime64
#   datetime_as_string
#   datetime_data
#   deg2rad
#   degrees
#   delete
#   deprecate
#   deprecate_with_doc
#   diag
#   diag_indices
#   diag_indices_from
#   diagflat
#   diagonal
#   diagonal
#   diff
#   digitize
#   disp
#   divide
#   dot
#   double
#   dsplit
#   dstack
#   dtype
#   e
#   ediff1d
#   einsum
#   emath
#   empty
#   empty_like
#   equal
#   errstate
#   euler_gamma
#   exp
#   exp2
#   expand_dims
#   expm1
#   extract
#   eye
#   fabs
#   fastCopyAndTranspose
#   fft
#   fill_diagonal
#   find_common_type
#   finfo
#   fix
#   flatiter
#   flatnonzero
#   flexible
#   fliplr
#   flipud
#   float128
#   float16
#   float32
#   float64
#   float_
#   floating
#   floor
#   floor_divide
#   fmax
#   fmin
#   fmod
#   format_parser
#   frexp
#   frombuffer
#   fromfile
#   fromfunction
#   fromiter
#   frompyfunc
#   fromregex
#   fromstring
#   full
#   full_like
#   fv
#   generic
#   genfromtxt
#   get_array_wrap
#   get_include
#   get_printoptions
#   getbufsize
#   geterr
#   geterrcall
#   geterrobj
#   gradient
#   greater
#   greater_equal
#   half
#   hamming
#   hanning
#   histogram
#   histogram2d
#   histogramdd
#   hsplit
#   hstack
#   hypot
#   i0
#   identity
#   iinfo
#   imag
#   in1d
#   index_exp
#   indices
#   inexact
#   inf
#   info
#   infty
#   inner
#   insert
#   int0
#   int16
#   int32
#   int64
#   int8
#   int_
#   int_asbuffer
#   intc
#   integer
#   interp
#   intersect1d
#   intp
#   invert
#   ipmt
#   irr
#   is_busday
#   isclose
#   iscomplex
#   iscomplexobj
#   isfinite
#   isfortran
#   isinf
#   isnan
#   isneginf
#   isposinf
#   isreal
#   isrealobj
#   isscalar
#   issctype
#   issubclass_
#   issubdtype
#   issubdtype
#   issubsctype
#   iterable
#   ix_
#   kaiser
#   kron
#   ldexp
#   left_shift
#   less
#   less_equal
#   lexsort
#   linalg
#   linspace
#   little_endian
#   load
#   load
#   loads
#   loads
#   loadtxt
#   log
#   log10
#   log1p
#   log2
#   logaddexp
#   logaddexp2
#   logical_and
#   logical_not
#   logical_or
#   logical_xor
#   logspace
#   longcomplex
#   longdouble
#   longfloat
#   longlong
#   lookfor
#   ma
#   mafromtxt
#   mask_indices
#   mat
#   math
#   matmul
#   matrix
#   maximum
#   maximum_sctype
#   may_share_memory
#   mean
#   mean
#   median
#   memmap
#   meshgrid
#   mgrid
#   min_scalar_type
#   minimum
#   mintypecode
#   mirr
#   mod
#   modf
#   moveaxis
#   msort
#   multiply
#   nan
#   nan_to_num
#   nanargmax
#   nanargmin
#   nanmax
#   nanmean
#   nanmedian
#   nanmin
#   nanpercentile
#   nanprod
#   nanstd
#   nansum
#   nanvar
#   nbytes
#   ndarray
#   ndenumerate
#   ndfromtxt
#   ndim
#   ndim
#   ndindex
#   nditer
#   negative
#   nested_iters
#   newaxis
#   nextafter
#   nonzero
#   nonzero
#   not_equal
#   nper
#   npv
#   number
#   obj2sctype
#   object0
#   object_
#   ogrid
#   ones
#   ones_like
#   outer
#   packbits
#   pad
#   partition
#   partition
#   percentile
#   pi
#   piecewise
#   place
#   pmt
#   poly
#   poly1d
#   polyadd
#   polyder
#   polydiv
#   polyfit
#   polyint
#   polymul
#   polysub
#   polyval
#   power
#   ppmt
#   prod
#   prod
#   product
#   product
#   promote_types
#   ptp
#   ptp
#   put
#   put
#   putmask
#   pv
#   r_
#   rad2deg
#   radians
#   random
#   rank
#   rank
#   rate
#   ravel
#   ravel
#   ravel_multi_index
#   real
#   real_if_close
#   rec
#   recarray
#   recfromcsv
#   recfromtxt
#   reciprocal
#   record
#   remainder
#   repeat
#   repeat
#   require
#   reshape
#   reshape
#   resize
#   resize
#   restoredot
#   result_type
#   right_shift
#   rint
#   roll
#   rollaxis
#   roots
#   rot90
#   round_
#   round_
#   row_stack
#   s_
#   safe_eval
#   save
#   savetxt
#   savez
#   savez_compressed
#   sctype2char
#   sctypeDict
#   sctypeNA
#   sctypes
#   searchsorted
#   searchsorted
#   select
#   set_numeric_ops
#   set_printoptions
#   set_string_function
#   setbufsize
#   setdiff1d
#   seterr
#   seterrcall
#   seterrobj
#   setxor1d
#   shape
#   shape
#   shares_memory
#   short
#   show_config
#   sign
#   signbit
#   signedinteger
#   sin
#   sinc
#   single
#   singlecomplex
#   sinh
#   size
#   size
#   sometrue
#   sometrue
#   sort
#   sort
#   sort_complex
#   source
#   spacing
#   split
#   sqrt
#   square
#   squeeze
#   squeeze
#   stack
#   std
#   std
#   str0
#   str_
#   string_
#   subtract
#   sum
#   sum
#   swapaxes
#   swapaxes
#   take
#   take
#   tan
#   tanh
#   tensordot
#   tile
#   timedelta64
#   trace
#   trace
#   transpose
#   transpose
#   trapz
#   tri
#   tril
#   tril_indices
#   tril_indices_from
#   trim_zeros
#   triu
#   triu_indices
#   triu_indices_from
#   true_divide
#   trunc
#   typeDict
#   typeNA
#   typecodes
#   typename
#   ubyte
#   ufunc
#   uint
#   uint0
#   uint16
#   uint32
#   uint64
#   uint8
#   uintc
#   uintp
#   ulonglong
#   unicode_
#   union1d
#   unique
#   unpackbits
#   unravel_index
#   unsignedinteger
#   unwrap
#   ushort
#   vander
#   var
#   var
#   vdot
#   vectorize
#   void
#   void0
#   vsplit
#   vstack
#   where
#   who
#   zeros
#   zeros_like
