# Stubs for numpy.dual (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from numpy.lib import i0 as i0

fft = ...  # type: Any
ifft = ...  # type: Any
fftn = ...  # type: Any
ifftn = ...  # type: Any
fft2 = ...  # type: Any
ifft2 = ...  # type: Any
norm = ...  # type: Any
inv = ...  # type: Any
svd = ...  # type: Any
solve = ...  # type: Any
det = ...  # type: Any
eig = ...  # type: Any
eigvals = ...  # type: Any
eigh = ...  # type: Any
eigvalsh = ...  # type: Any
lstsq = ...  # type: Any
pinv = ...  # type: Any
cholesky = ...  # type: Any
