# Stubs for numpy.distutils.lib2def (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

__doc__ = ...  # type: str
py_ver = ...  # type: Any
DEFAULT_NM = ...  # type: str
DEF_HEADER = ...  # type: Any
FUNC_RE = ...  # type: Any
DATA_RE = ...  # type: Any

def parse_cmd(): ...
def getnm(nm_cmd: Any = ...): ...
def parse_nm(nm_output): ...
def output_def(dlist, flist, header, file: Any = ...): ...
