# Stubs for numpy.distutils.numpy_distribution (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from distutils.core import Distribution

class NumpyDistribution(Distribution):
    scons_data = ...  # type: Any
    installed_libraries = ...  # type: Any
    installed_pkg_config = ...  # type: Any
    def __init__(self, attrs: Optional[Any] = ...) -> None: ...
    def has_scons_scripts(self): ...
