# Stubs for numpy.distutils.command.bdist_rpm (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from setuptools.command.bdist_rpm import bdist_rpm as old_bdist_rpm
from distutils.command.bdist_rpm import bdist_rpm as old_bdist_rpm

class bdist_rpm(old_bdist_rpm): ...
