# Stubs for numpy.distutils.command.develop (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from setuptools.command.develop import develop as old_develop

class develop(old_develop):
    __doc__ = ...  # type: Any
    def install_for_development(self): ...
