# Stubs for numpy.distutils.command.egg_info (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from setuptools.command.egg_info import egg_info as _egg_info

class egg_info(_egg_info):
    def run(self): ...
