# Stubs for numpy.distutils.command.install_data (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from distutils.command.install_data import install_data as old_install_data

have_setuptools = ...  # type: Any

class install_data(old_install_data):
    def run(self): ...
    def finalize_options(self): ...
