# Stubs for numpy.distutils.command.install (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

have_setuptools = ...  # type: bool
old_install = ...  # type: Any

class install(old_install):
    sub_commands = ...  # type: Any
    install_lib = ...  # type: Any
    def finalize_options(self): ...
    def setuptools_run(self): ...
    def run(self): ...
