# Stubs for numpy.doc (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

__doc__ = ...  # type: Any

# Names in __all__ with no definition:
#   basics
#   broadcasting
#   byteswapping
#   constants
#   creation
#   glossary
#   indexing
#   internals
#   misc
#   structured_arrays
#   subclassing
#   ufuncs
