# Stubs for numpy.distutils.fcompiler.none (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from numpy.distutils.fcompiler import FCompiler

compilers = ...  # type: Any

class NoneFCompiler(FCompiler):
    compiler_type = ...  # type: str
    description = ...  # type: str
    executables = ...  # type: Any
    def find_executables(self): ...
