# Stubs for numpy.distutils.fcompiler.pg (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from numpy.distutils.fcompiler import FCompiler

compilers = ...  # type: Any

class PGroupFCompiler(FCompiler):
    compiler_type = ...  # type: str
    description = ...  # type: str
    version_pattern = ...  # type: str
    executables = ...  # type: Any
    pic_flags = ...  # type: Any
    module_dir_switch = ...  # type: str
    module_include_switch = ...  # type: str
    def get_flags(self): ...
    def get_flags_opt(self): ...
    def get_flags_debug(self): ...
    def get_flags_linker_so(self): ...
    def runtime_library_dir_option(self, dir): ...
