# Stubs for numpy.distutils.fcompiler.ibm (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from numpy.distutils.fcompiler import FCompiler

compilers = ...  # type: Any

class IBMFCompiler(FCompiler):
    compiler_type = ...  # type: str
    description = ...  # type: str
    version_pattern = ...  # type: str
    executables = ...  # type: Any
    version = ...  # type: Any
    def get_version(self, *args, **kwds): ...
    def get_flags(self): ...
    def get_flags_debug(self): ...
    def get_flags_linker_so(self): ...
    def get_flags_opt(self): ...
