# Stubs for numpy.distutils.fcompiler.nag (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from numpy.distutils.fcompiler import FCompiler

compilers = ...  # type: Any

class NAGFCompiler(FCompiler):
    compiler_type = ...  # type: str
    description = ...  # type: str
    version_pattern = ...  # type: str
    executables = ...  # type: Any
    def get_flags_linker_so(self): ...
    def get_flags_opt(self): ...
    def get_flags_arch(self): ...
    def get_flags_debug(self): ...
