# Stubs for numpy.distutils.fcompiler.sun (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from numpy.distutils.fcompiler import FCompiler

compilers = ...  # type: Any

class SunFCompiler(FCompiler):
    compiler_type = ...  # type: str
    description = ...  # type: str
    version_match = ...  # type: Any
    executables = ...  # type: Any
    module_dir_switch = ...  # type: str
    module_include_switch = ...  # type: str
    pic_flags = ...  # type: Any
    def get_flags_f77(self): ...
    def get_opt(self): ...
    def get_arch(self): ...
    def get_libraries(self): ...
    def runtime_library_dir_option(self, dir): ...
