# Stubs for numpy.distutils.fcompiler.vast (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from numpy.distutils.fcompiler.gnu import GnuFCompiler

compilers = ...  # type: Any

class VastFCompiler(GnuFCompiler):
    compiler_type = ...  # type: str
    compiler_aliases = ...  # type: Any
    description = ...  # type: str
    version_pattern = ...  # type: str
    object_switch = ...  # type: str
    executables = ...  # type: Any
    module_dir_switch = ...  # type: Any
    module_include_switch = ...  # type: Any
    def find_executables(self): ...
    def get_version_cmd(self): ...
    version = ...  # type: Any
    def get_flags_arch(self): ...
