# Stubs for numpy.doc.constants (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

constants = ...  # type: Any

def add_newdoc(module, name, doc): ...

constants_str = ...  # type: Any
s = ...  # type: Any
lines = ...  # type: Any
new_lines = ...  # type: Any
m = ...  # type: Any
prev = ...  # type: Any
__doc__ = ...  # type: Any
