# Stubs for numpy.core.info (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

depends = ...  # type: Any
global_symbols = ...  # type: Any
