# Stubs for numpy.core.memmap (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from .numeric import ndarray

class memmap(ndarray):
    __array_priority__ = ...  # type: Any
    offset = ...  # type: Any
    mode = ...  # type: Any
    filename = ...  # type: Any
    def __new__(subtype, filename, dtype: Any = ..., mode: str = ..., offset: int = ..., shape: Optional[Any] = ..., order: str = ...): ...
    def __array_finalize__(self, obj): ...
    def flush(self): ...
