# Stubs for numpy.core.numerictypes (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from numpy.compat import long as long
from numpy.core.multiarray import datetime_data as datetime_data, datetime_as_string as datetime_as_string, busday_offset as busday_offset, busday_count as busday_count, is_busday as is_busday, busdaycalendar as busdaycalendar

sctypeDict = ...  # type: Any
sctypeNA = ...  # type: Any
void = ...  # type: Any
generic = ...  # type: Any
sctypes = ...  # type: Any

def maximum_sctype(t): ...
def issctype(rep): ...
def obj2sctype(rep, default: Optional[Any] = ...): ...
def issubdtype(arg1, arg2): ...

class _typedict(dict):
    def __getitem__(self, obj): ...

nbytes = ...  # type: Any

def sctype2char(sctype): ...

cast = ...  # type: Any
ScalarType = ...  # type: Any
typecodes = ...  # type: Any
typeDict = ...  # type: Any
typeNA = ...  # type: Any

def find_common_type(array_types, scalar_types): ...

# Names in __all__ with no definition:
bool8= Any
bool_= Any
byte= Any
bytes0= Any
bytes_= Any
cdouble= Any
cfloat= Any
character= Any
clongdouble= Any
clongfloat= Any
complex128= Any
complex256= Any
complex64= Any
complex_= Any
complexfloating= Any
csingle= Any
datetime64= Any
double= Any
flexible= Any
float128= Any
float16= Any
float32= Any
float64= Any
float_= Any
floating= Any
half= Any
inexact= Any
int0= Any
int16= Any
int32= Any
int64= Any
int8= Any
int_= Any
intc= Any
integer= Any
intp= Any
longcomplex= Any
longdouble= Any
longfloat= Any
longlong= Any
number= Any
object0= Any
object_= Any
short= Any
signedinteger= Any
single= Any
singlecomplex= Any
str0= Any
str_= Any
string_= Any
timedelta64= Any
ubyte= Any
uint= Any
uint0= Any
uint16= Any
uint32= Any
uint64= Any
uint8= Any
uintc= Any
uintp= Any
ulonglong= Any
unicode_= Any
unsignedinteger= Any
ushort= Any
void0= Any
