# Stubs for numpy.core.umath_tests (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

euclidean_pdist = ... # type: Any
inner1d = ... # type: Any
innerwt = ... # type: Any
matrix_multiply = ... # type: Any

def test_signature(*args, **kwargs): ...
