# Stubs for numpy.f2py (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

run_main = ...  # type: Any

def compile(source, modulename: str = ..., extra_args: str = ..., verbose: bool = ..., source_fn: Optional[Any] = ..., extension: str = ...): ...

# Names in __all__ with no definition:
#   f2py_testing
