# Stubs for numpy.compat (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._inspect import getargspec as getargspec, formatargspec as formatargspec
from .py3k import *

# Names in __all__ with no definition:
#   asbytes
#   asbytes_nested
#   asstr
#   asunicode
#   asunicode_nested
#   basestring
#   bytes
#   getexception
#   integer_types
#   isfileobj
#   long
#   npy_load_module
#   open_latin1
#   sixu
#   strchar
#   unicode
