# Stubs for numpy.compat.setup (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def configuration(parent_package: str = ..., top_path: Optional[Any] = ...): ...
