# Stubs for numpy.distutils.command (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Names in __all__ with no definition:
#   bdist
#   bdist_dumb
#   bdist_rpm
#   bdist_wininst
#   build
#   build_clib
#   build_ext
#   build_py
#   build_scripts
#   build_src
#   clean
#   config
#   config_compiler
#   install
#   install_clib
#   install_data
#   install_headers
#   install_lib
#   install_scripts
#   sdist
