# Stubs for numpy.distutils.command.build (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from distutils.command.build import build as old_build

class build(old_build):
    sub_commands = ...  # type: Any
    user_options = ...  # type: Any
    help_options = ...  # type: Any
    fcompiler = ...  # type: Any
    parallel = ...  # type: Any
    def initialize_options(self): ...
    build_scripts = ...  # type: Any
    def finalize_options(self): ...
    def run(self): ...
