# Stubs for numpy.distutils.command.install_clib (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from distutils.core import Command

class install_clib(Command):
    description = ...  # type: str
    user_options = ...  # type: Any
    install_dir = ...  # type: Any
    outfiles = ...  # type: Any
    def initialize_options(self): ...
    def finalize_options(self): ...
    def run(self): ...
    def get_outputs(self): ...
