# Stubs for numpy.distutils.command.install_headers (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from distutils.command.install_headers import install_headers as old_install_headers

class install_headers(old_install_headers):
    def run(self): ...
