# Stubs for numpy.distutils.command.sdist (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from setuptools.command.sdist import sdist as old_sdist
from distutils.command.sdist import sdist as old_sdist

class sdist(old_sdist):
    def add_defaults(self): ...
